export type TornMember = {
  level: number;
  gender: string;
  player_id: number;
  name: string;
  rank: string;
  property: string;
  signup: string;
  awards: number;
  friends: number;
  enemies: number;
  forum_posts: number;
  karma: number;
  age: number;
  role: string;
  donator: number;
  property_id: number;
  competition: any;
  revivable: number;
  status: Status;
  bazaar: any;
  criminalrecord: CriminalRecord;
  discord: Discord;
  display: any;
  personalstats: Personalstats;
  life: Life;
  job: Job;
  faction: Faction;
  married: Married;
  states: States;
  last_action: LastAction;
};

type Status = {
  description: string;
  details: string;
  state: string;
  color: string;
  until: number;
};

type CriminalRecord = {
  selling_illegal_products: number;
  theft: number;
  auto_theft: number;
  drug_deals: number;
  computer_crimes: number;
  murder: number;
  fraud_crimes: number;
  other: number;
  total: number;
};

type Discord = {
  userID: number;
  discordID: string;
};

type Personalstats = {
  bazaarcustomers: number;
  bazaarsales: number;
  bazaarprofit: number;
  useractivity: number;
  activestreak: number;
  bestactivestreak: number;
  itemsbought: number;
  pointsbought: number;
  itemsboughtabroad: number;
  moneyinvested: number;
  investedprofit: number;
  weaponsbought: number;
  trades: number;
  itemssent: number;
  auctionswon: number;
  auctionsells: number;
  pointssold: number;
  attackswon: number;
  attackslost: number;
  attacksdraw: number;
  bestkillstreak: number;
  killstreak: number;
  moneymugged: number;
  attacksstealthed: number;
  attackhits: number;
  attackmisses: number;
  attackdamage: number;
  attackcriticalhits: number;
  respectforfaction: number;
  onehitkills: number;
  defendswon: number;
  defendslost: number;
  defendsstalemated: number;
  bestdamage: number;
  roundsfired: number;
  yourunaway: number;
  theyrunaway: number;
  highestbeaten: number;
  peoplebusted: number;
  failedbusts: number;
  peoplebought: number;
  peopleboughtspent: number;
  virusescoded: number;
  cityfinds: number;
  traveltimes: number;
  bountiesplaced: number;
  bountiesreceived: number;
  bountiescollected: number;
  totalbountyreward: number;
  revives: number;
  revivesreceived: number;
  medicalitemsused: number;
  statenhancersused: number;
  trainsreceived: number;
  totalbountyspent: number;
  drugsused: number;
  overdosed: number;
  meritsbought: number;
  personalsplaced: number;
  classifiedadsplaced: number;
  mailssent: number;
  friendmailssent: number;
  factionmailssent: number;
  companymailssent: number;
  spousemailssent: number;
  largestmug: number;
  cantaken: number;
  exttaken: number;
  kettaken: number;
  lsdtaken: number;
  opitaken: number;
  shrtaken: number;
  spetaken: number;
  pcptaken: number;
  xantaken: number;
  victaken: number;
  chahits: number;
  heahits: number;
  axehits: number;
  grehits: number;
  machits: number;
  pishits: number;
  rifhits: number;
  shohits: number;
  smghits: number;
  piehits: number;
  slahits: number;
  argtravel: number;
  mextravel: number;
  dubtravel: number;
  hawtravel: number;
  japtravel: number;
  lontravel: number;
  soutravel: number;
  switravel: number;
  chitravel: number;
  cantravel: number;
  dumpfinds: number;
  dumpsearches: number;
  itemsdumped: number;
  daysbeendonator: number;
  caytravel: number;
  jailed: number;
  hospital: number;
  attacksassisted: number;
  bloodwithdrawn: number;
  networth: number;
  missionscompleted: number;
  contractscompleted: number;
  dukecontractscompleted: number;
  missioncreditsearned: number;
  consumablesused: number;
  candyused: number;
  alcoholused: number;
  energydrinkused: number;
  nerverefills: number;
  unarmoredwon: number;
  h2hhits: number;
  organisedcrimes: number;
  territorytime: number;
  territoryjoins: number;
  stockpayouts: number;
  stockprofits: number;
  stocklosses: number;
  stockfees: number;
  stocknetprofits: number;
  arrestsmade: number;
  tokenrefills: number;
  booksread: number;
  traveltime: number;
  boostersused: number;
  rehabs: number;
  rehabcost: number;
  awards: number;
  receivedbountyvalue: number;
  networthpending: number;
  networthwallet: number;
  networthbank: number;
  networthpoints: number;
  networthcayman: number;
  networthvault: number;
  networthpiggybank: number;
  networthitems: number;
  networthdisplaycase: number;
  networthbazaar: number;
  networthproperties: number;
  networthstockmarket: number;
  networthitemmarket: number;
  networthauctionhouse: number;
  networthcompany: number;
  networthbookie: number;
  networthenlistedcars: number;
  networthloan: number;
  networthunpaidfees: number;
  racingskill: number;
  raceswon: number;
  racesentered: number;
  racingpointsearned: number;
  specialammoused: number;
  cityitemsbought: number;
  hollowammoused: number;
  tracerammoused: number;
  piercingammoused: number;
  incendiaryammoused: number;
  attackswonabroad: number;
  defendslostabroad: number;
  rankedwarringwins: number;
  retals: number;
  elo: number;
  strength: number;
  defense: number;
  speed: number;
  dexterity: number;
  totalstats: number;
  manuallabor: number;
  intelligence: number;
  endurance: number;
  totalworkingstats: number;
  jobpointsused: number;
  reviveskill: number;
  itemslooted: number;
  rankedwarhits: number;
  raidhits: number;
  territoryclears: number;
  refills: number;
};

type Life = {
  current: number;
  maximum: number;
  increment: number;
  interval: number;
  ticktime: number;
  fulltime: number;
};

type Job = {
  position: string;
  company_id: number;
  company_name: string;
  company_type: number;
};

type Faction = {
  position: string;
  faction_id: number;
  days_in_faction: number;
  faction_name: string;
  faction_tag: string;
};

type Married = {
  spouse_id: number;
  spouse_name: string;
  duration: number;
};

type States = {
  hospital_timestamp: number;
  jail_timestamp: number;
};

type LastAction = {
  status: string;
  timestamp: number;
  relative: string;
};
